# Generated by Django 5.0.4 on 2024-04-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('acode', models.CharField(max_length=11)),
                ('registration', models.ImageField(upload_to='registration')),
                ('medical_registration', models.ImageField(upload_to='medical_registration')),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
                ('description', models.TextField()),
                ('service_price', models.FloatField(default=100)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.specialties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
